### ISSUE TITLE
Mem Leak in the Uart Simulation

### ISSUE THREAD

**Issue by nik-ang** [SpaceTeam/STS1_EDU_Scheduler#55]
The `UARTSimHandle` and the `COBCSim` are connected to eachother via two `Arc<RwLock<T>>` pointers which will lead to a memory leak exactly once per use, because the pointer counters of the `Arc`s will never reach zero.

**Easy fix:**

1.  Replace the `raspi`'s datatype in the `COBCSim` struct to a `Weak` Pointer instead.
2. Fix dereferencing errors that might come up.

_Obs: This might look like the `COBCSim` is the more important strcut. However, the owner of the `Arc` pointer is the boss. Assert our symbolical dominance as EDU Module by making the `UARTSimHandle` the owner of the `Arc`._

**Comment by florg-32** [comment]
@nik-ang do you plan to continue working on this task?

**Comment by florg-32** [comment]
@nik-ang left us :(
