### ISSUE TITLE
Properly define error management

### ISSUE THREAD

**Issue by florg-32** [SpaceTeam/STS1_EDU_Scheduler#89]
Currently, the way the EDU manages errors is quite random. Some events are ignored (e.g. failure to truncate result files), while others are logged (e.g. cant create student process) and some panic (e.g. communication handle cant do something).

We should discuss and define how all of this should be handled exactly.

**Comment by florg-32** [comment]
I started to look at all the different errors that can happen during operation of the scheduler and wrote some of them down in the PDD page 21ff. Please have a look and see if you agree with how they should be handled. @PatrickKa @WagnerDavid @orbitalfox

**Comment by orbitalfox** [comment]
One way to structure the "Error Categories" (PDD 6.2.1) and "Error Management" (PDD 6.2.2) is to do a _Failure Mode and Effects Analysis_ (FMEA). ECSS offers the standard [ECSS-Q-ST-30-02C ](https://ecss.nl/standard/ecss-q-st-30-02c-failure-modes-effects-and-criticality-analysis-fmeafmeca/) for this purpose, which could simplify for our purposes.

**Comment by florg-32** [comment]
Ah yes, I wanted to do an FMEA some time ago, but was to lazy. I will look
into starting it in the PDD.

orbitalfox ***@***.***> schrieb am So., 12. Feb. 2023, 03:53:

**Comment by florg-32** [comment]
More or less done
